# Generated by Django 6.0.1 on 2026-02-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='visible',
            new_name='is_visible',
        ),
    ]
