# Generated by Django 6.0.1 on 2026-02-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productreview_unique_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-updated_at']},
        ),
    ]
