# Generated by Django 6.0.1 on 2026-01-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_session_key'),
        ('store', '0005_alter_variation_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, related_name='+', to='store.variation'),
        ),
    ]
