# Generated by Django 6.0.1 on 2026-02-03 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderproduct_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'ordering': ['-updated_at']},
        ),
    ]
