# Generated by Django 6.0.1 on 2026-01-31 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_payment_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='variation',
            new_name='variations',
        ),
    ]
